[[IgnoredVulns]]
id = "GHSA-vg35-5wq7-3x7w"
reason = "Already fixed"

[[IgnoredVulns]]
id = "GHSA-q742-qvgc-gc2f"
reason = "Already fixed"

[[IgnoredVulns]]
id = "GHSA-v98h-vmpc-fpqv"
reason = "Already fixed"