/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  myAutogeneratedSidebar: [{type: 'autogenerated', dirName: '.'}],

  /*myAutogeneratedSidebar: [{
	type: 'category',
	link:  {type: 'doc', id: 'root'},
	label: 'Pimcore Packages', 
	items: [
		{ 
			type: 'category', 
			label: 'Portal Engine',
			link: {type: 'doc', id: 'Portal_Engine/README'},
			collapsible: true,
			items: [
				{type: 'autogenerated', dirName: '01_Portal_Engine'}	
			]
		},
		{ 
			type: 'category', 
			label: 'Advanced Object Search',
			link: {type: 'doc', id: 'Advanced_Object_Search/README'},
			collapsible: true,
			items: [
				{type: 'autogenerated', dirName: '02_Advanced_Object_Search'}	
			]
		}		
	
		
    ]
  }]*/

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
