const platformVersions = {
    '2023.3': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultSidebarSection: 'Pimcore Extensions',
        repos: {
            'pimcore/pimcore': {
                branch: 'v11.1.6',
                readmeEditBranch: '11.2',
                copyReadme: false,
                targetDirectory: '01_Pimcore',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/platform-version': {
                branch: '2023.3',
                copyReadme: true,
                targetDirectory: '02_Platform_Version',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/admin-ui-classic-light-theme-bundle': {
                branch: '1.0',
                copyReadme: true,
                targetDirectory: '05_Light_Theme_Admin_UI',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: 'v3.1.8',
                copyReadme: true,
                targetDirectory: '05_Portal_Engine',
                enterprise: true,
            },
            'pimcore/data-hub': {
                branch: 'v1.6.6',
                readmeEditBranch: '1.x',
                copyReadme: true,
                targetDirectory: '10_Datahub',
                enterprise: false,
            },
            'pimcore/data-importer': {
                branch: 'v1.8.9',
                copyReadme: true,
                targetDirectory: '11_Data_Importer',
                enterprise: false,
            },
            'pimcore/data-hub-file-export': {
                branch: 'v2.0.4',
                copyReadme: true,
                targetDirectory: '12_Datahub_File_Export',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: 'v2.0.7',
                copyReadme: true,
                targetDirectory: '13_Datahub_Simple_Rest',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '14_Datahub_Productsup',
                enterprise: true,
            },
            'pimcore/data-hub-ci-hub': {
                branch: 'v1.2.2',
                copyReadme: true,
                targetDirectory: '15_Datahub_CI_Hub',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: 'v2.0.10',
                copyReadme: true,
                targetDirectory: '20_Enterprise_Metadata',
                enterprise: true,
            },
            'pimcore/direct-edit': {
                branch: 'v2.0.5',
                copyReadme: true,
                targetDirectory: '21_Direct_Edit',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: 'v1.1.2',
                copyReadme: true,
                targetDirectory: '25_Worfklow_Designer',
                enterprise: true,
            },
            'pimcore/headless-documents': {
                branch: 'v2.1.5',
                copyReadme: true,
                targetDirectory: '30_Headless_Documents',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                branch: 'v1.1.7',
                copyReadme: true,
                targetDirectory: '32_OpenID_Connect',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: 'v3.0.6',
                copyReadme: true,
                targetDirectory: '34_Translation_Provider_Interfaces',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '36_Statistics_Explorer',
                enterprise: true,
            },
            'pimcore/ecommerce-framework-bundle': {
                branch: 'v1.0.14',
                copyReadme: true,
                targetDirectory: '37_Ecommerce_Framework',
                enterprise: false,
            },
            'pimcore/personalization-bundle': {
                branch: 'v1.0.3',
                readmeEditBranch: '1.x',
                copyReadme: true,
                targetDirectory: '38_Targeting',
                enterprise: false,
            },
            'pimcore/newsletter-bundle': {
                branch: '1.1',
                copyReadme: true,
                targetDirectory: '39_Newsletter',
                enterprise: false,
            },
            'pimcore/customer-data-framework': {
                branch: '4.0',
                copyReadme: true,
                targetDirectory: '40_Customer_Management_Framework',
                enterprise: false,
            },
            'pimcore/google-marketing-bundle': {
                branch: 'v1.0.3',
                readmeEditBranch: '1.x',
                copyReadme: true,
                targetDirectory: '41_Google_Marketing',
                enterprise: false,
            },
            'pimcore/web-to-print-bundle': {
                branch: 'v1.1.2',
                readmeEditBranch: '1.x',
                copyReadme: true,
                targetDirectory: '45_Web_To_Print',
                enterprise: false,
            },
            'pimcore/advanced-object-search': {
                branch: 'v5.0.6',
                readmeEditBranch: '6.x',
                copyReadme: true,
                targetDirectory: '46_Advanced_Object_Search',
                enterprise: false,
            },
            'pimcore/perspective-editor': {
                branch: '1.7',
                copyReadme: true,
                targetDirectory: '48_Perspective_Editor',
                enterprise: false,
            },
            'pimcore/data-quality-management-bundle': {
                branch: 'v1.1.3',
                copyReadme: true,
                targetDirectory: '26_Data_Quality_Management',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: 'v1.1.3',
                copyReadme: true,
                targetDirectory: '27_Backend_Power_Tools',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: 'v1.0.2',
                copyReadme: true,
                targetDirectory: '16_Datahub_Webhooks',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: 'v1.0.7',
                copyReadme: true,
                targetDirectory: '30_Workflow_Automation',
                enterprise: true,
            },
        }
    },
    '2024.4': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultSidebarSection: 'Pimcore Extensions',
        repos: {
            'pimcore/platform-version': {
                branch: '2024.4',
                copyReadme: true,
                targetDirectory: '0001_Platform_Version',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/pimcore': {
                branch: 'v11.5.14.1',
                copyReadme: false,
                targetDirectory: '0002_Pimcore',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/data-hub': {
                branch: '1.9',
                copyReadme: true,
                targetDirectory: '0101_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-importer': {
                branch: '1.10',
                copyReadme: true,
                targetDirectory: '0102_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-hub-file-export': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0103_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: '3.1',
                copyReadme: true,
                targetDirectory: '0104_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: '1.3',
                copyReadme: true,
                targetDirectory: '0105_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/admin-ui-classic-light-theme-bundle': {
                branch: '1.0',
                copyReadme: true,
                targetDirectory: '0201_Light_Theme_Admin_UI',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: '1.2',
                copyReadme: true,
                targetDirectory: '0202_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/perspective-editor': {
                branch: '1.8',
                copyReadme: true,
                targetDirectory: '0203_Perspective_Editor',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/direct-edit': {
                branch: '2.1',
                copyReadme: true,
                targetDirectory: '0204_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: 'v1.4.2',
                copyReadme: true,
                targetDirectory: '0205_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/advanced-object-search': {
                branch: '6.1',
                copyReadme: true,
                targetDirectory: '0206_Advanced_Object_Search',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/copilot-bundle': {
                branch: '1.3',
                copyReadme: true,
                targetDirectory: '0301_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                branch: 'v1.2.2',
                copyReadme: true,
                targetDirectory: '0302_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: 'v1.0.7',
                copyReadme: true,
                targetDirectory: '0303_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: '4.2',
                copyReadme: true,
                targetDirectory: '0401_Portal_Engine',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0402_Statistics_Explorer',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/headless-documents': {
                branch: '2.3',
                copyReadme: true,
                targetDirectory: '0501_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0502_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                branch: '1.2',
                copyReadme: true,
                targetDirectory: '0503_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/web-to-print-bundle': {
                branch: '1.4',
                copyReadme: true,
                targetDirectory: '0504_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/customer-data-framework': {
                branch: '4.2',
                copyReadme: true,
                targetDirectory: '0505_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/generic-data-index-bundle': {
                branch: '1.3',
                copyReadme: true,
                targetDirectory: '0506_Generic_Data_Index',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/newsletter-bundle': {
                branch: '1.2',
                copyReadme: true,
                targetDirectory: '0601_Newsletter',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/google-marketing-bundle': {
                branch: '1.1',
                copyReadme: true,
                targetDirectory: '0602_Google_Marketing',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/personalization-bundle': {
                branch: '1.1',
                copyReadme: true,
                targetDirectory: '0603_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/openid-connect': {
                branch: '1.2',
                copyReadme: true,
                targetDirectory: '0701_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: '3.1',
                copyReadme: true,
                targetDirectory: '0702_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0703_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-ci-hub': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0704_Datahub_CI_Hub',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ecommerce-framework-bundle': {
                branch: '1.3',
                copyReadme: true,
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: false,
            },
            'pimcore/quill-bundle': {
                branch: '1.0',
                copyReadme: true,
                targetDirectory: '0500_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/paas': {
                branch: '1.x',
                copyReadme: true,
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
        }
    },
    '2025.1': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultSidebarSection: 'Pimcore Extensions',
        repos: {
            'pimcore/platform-version': {
                branch: '2025.1',
                copyReadme: true,
                targetDirectory: '0001_Platform_Version',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/pimcore': {
                branch: 'v12.0.4',
                copyReadme: false,
                targetDirectory: '0002_Pimcore',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/studio-backend-bundle': {
                branch: 'v0.5.20',
                copyReadme: true,
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/studio-ui-bundle': {
                branch: 'v0.5.20',
                copyReadme: true,
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/data-hub': {
                branch: 'v2.0.1',
                copyReadme: true,
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-importer': {
                branch: 'v2.0.1',
                copyReadme: true,
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-hub-file-export': {
                branch: 'v3.0.1',
                copyReadme: true,
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: 'v3.2.2',
                copyReadme: true,
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/admin-ui-classic-light-theme-bundle': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '0301_Light_Theme_Admin_UI',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: 'v1.3.0',
                copyReadme: true,
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/perspective-editor': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0303_Perspective_Editor',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/direct-edit': {
                branch: 'v2.3.0',
                copyReadme: true,
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: 'v1.6.0',
                copyReadme: true,
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/advanced-object-search': {
                branch: '7.0',
                copyReadme: true,
                targetDirectory: '0306_Advanced_Object_Search',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/copilot-bundle': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: 'v1.1.0',
                copyReadme: true,
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: 'v5.0.2',
                copyReadme: true,
                targetDirectory: '0501_Portal_Engine',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: 'v3.0.0',
                copyReadme: true,
                targetDirectory: '0502_Statistics_Explorer',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/quill-bundle': {
                branch: 'v2.0.1',
                copyReadme: true,
                targetDirectory: '0600_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/headless-documents': {
                branch: 'v2.4.0',
                copyReadme: true,
                targetDirectory: '0601_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: 'v3.0.3',
                copyReadme: true,
                targetDirectory: '0602_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                branch: 'v1.3.0',
                copyReadme: true,
                targetDirectory: '0603_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0604_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                branch: 'v5.0.1',
                copyReadme: true,
                targetDirectory: '0605_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/generic-data-index-bundle': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '0606_Generic_Data_Index',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/newsletter-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0701_Newsletter',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/google-marketing-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0702_Google_Marketing',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/ee-personalization-bundle': {
                branch: 'v2.0.1',
                copyReadme: true,
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                branch: 'v1.4.0',
                copyReadme: true,
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: 'v4.0.1',
                copyReadme: true,
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: 'v2.3.1',
                copyReadme: true,
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '1.x',
                copyReadme: true,
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
        }
    },
    '2025.2': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultSidebarSection: 'Pimcore Extensions',
        repos: {
            'pimcore/platform-version': {
                branch: '2025.2',
                copyReadme: true,
                targetDirectory: '0001_Platform_Version',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/pimcore': {
                branch: 'v12.1.5',
                copyReadme: false,
                targetDirectory: '0002_Pimcore',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/studio-backend-bundle': {
                branch: 'v0.6.30',
                copyReadme: true,
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/studio-ui-bundle': {
                branch: 'v0.6.30',
                copyReadme: true,
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/data-hub': {
                branch: 'v2.1.1',
                copyReadme: true,
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-importer': {
                branch: 'v2.1.2',
                copyReadme: true,
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-hub-file-export': {
                branch: 'v3.1.2',
                copyReadme: true,
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: 'v3.2.2',
                copyReadme: true,
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/admin-ui-classic-light-theme-bundle': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '0301_Light_Theme_Admin_UI',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: 'v1.4.2',
                copyReadme: true,
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/perspective-editor': {
                branch: 'v2.1.0',
                copyReadme: true,
                targetDirectory: '0303_Perspective_Editor',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/direct-edit': {
                branch: 'v2.4.0',
                copyReadme: true,
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: 'v1.6.0',
                copyReadme: true,
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/advanced-object-search': {
                branch: '7.0',
                copyReadme: true,
                targetDirectory: '0306_Advanced_Object_Search',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/copilot-bundle': {
                branch: 'v2.1.1',
                copyReadme: true,
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: 'v1.1.0',
                copyReadme: true,
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: 'v5.1.5',
                copyReadme: true,
                targetDirectory: '0501_Portal_Engine',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: 'v3.1.1',
                copyReadme: true,
                targetDirectory: '0502_Statistics_Explorer',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/quill-bundle': {
                branch: 'v2.1.2',
                copyReadme: true,
                targetDirectory: '0600_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/headless-documents': {
                branch: 'v2.5.0',
                copyReadme: true,
                targetDirectory: '0601_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: 'v3.1.3',
                copyReadme: true,
                targetDirectory: '0602_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                branch: 'v1.4.1',
                copyReadme: true,
                targetDirectory: '0603_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                branch: 'v2.1.0',
                copyReadme: true,
                targetDirectory: '0604_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                branch: 'v5.1.0',
                copyReadme: true,
                targetDirectory: '0605_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/generic-data-index-bundle': {
                branch: 'v2.1.2',
                copyReadme: true,
                targetDirectory: '0606_Generic_Data_Index',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/newsletter-bundle': {
                branch: 'v2.1.1',
                copyReadme: true,
                targetDirectory: '0701_Newsletter',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/google-marketing-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0702_Google_Marketing',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/ee-personalization-bundle': {
                branch: 'v2.1.0',
                copyReadme: true,
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                branch: 'v1.4.0',
                copyReadme: true,
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: 'v4.1.1',
                copyReadme: true,
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: 'v2.3.1',
                copyReadme: true,
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                branch: 'v2.1.1',
                copyReadme: true,
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '1.x',
                copyReadme: true,
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
        }
    },
    '2025.3': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultSidebarSection: 'Pimcore Extensions',
        repos: {
            'pimcore/platform-version': {
                branch: '2025.3',
                copyReadme: true,
                targetDirectory: '0001_Platform_Version',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/pimcore': {
                branch: 'v12.2.4',
                copyReadme: false,
                targetDirectory: '0002_Pimcore',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/studio-backend-bundle': {
                branch: 'v0.10.21',
                copyReadme: true,
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/studio-ui-bundle': {
                branch: 'v0.10.21',
                copyReadme: true,
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/data-hub': {
                branch: 'v2.2.1',
                copyReadme: true,
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-importer': {
                branch: 'v2.2.0',
                copyReadme: true,
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-hub-file-export': {
                branch: 'v3.2.2',
                copyReadme: true,
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: 'v3.3.1',
                copyReadme: true,
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/admin-ui-classic-light-theme-bundle': {
                branch: 'v2.0.2',
                copyReadme: true,
                targetDirectory: '0301_Light_Theme_Admin_UI',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: 'v1.5.0',
                copyReadme: true,
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/perspective-editor': {
                branch: 'v2.1.0',
                copyReadme: true,
                targetDirectory: '0303_Perspective_Editor',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/direct-edit': {
                branch: 'v2.5.0',
                copyReadme: true,
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: 'v1.7.0',
                copyReadme: true,
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/advanced-object-search': {
                branch: '7.0',
                copyReadme: true,
                targetDirectory: '0306_Advanced_Object_Search',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/copilot-bundle': {
                branch: 'v2.2.0',
                copyReadme: true,
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: 'v1.1.0',
                copyReadme: true,
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: 'v5.1.5',
                copyReadme: true,
                targetDirectory: '0501_Portal_Engine',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: 'v3.1.1',
                copyReadme: true,
                targetDirectory: '0502_Statistics_Explorer',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/ee-tinymce-bundle': {
                branch: 'v2.0.4',
                copyReadme: true,
                targetDirectory: '0600_TinyMCE_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: 'professional',
            },
            'pimcore/quill-bundle': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0601_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/headless-documents': {
                branch: 'v2.5.0',
                copyReadme: true,
                targetDirectory: '0602_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: 'v3.2.1',
                copyReadme: true,
                targetDirectory: '0603_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                branch: 'v1.5.0',
                copyReadme: true,
                targetDirectory: '0604_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                branch: 'v2.1.0',
                copyReadme: true,
                targetDirectory: '0605_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                branch: 'v5.1.0',
                copyReadme: true,
                targetDirectory: '0606_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/generic-data-index-bundle': {
                branch: 'v2.2.2',
                copyReadme: true,
                targetDirectory: '0607_Generic_Data_Index',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/newsletter-bundle': {
                branch: 'v2.2.0',
                copyReadme: true,
                targetDirectory: '0701_Newsletter',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/google-marketing-bundle': {
                branch: 'v2.0.0',
                copyReadme: true,
                targetDirectory: '0702_Google_Marketing',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/ee-personalization-bundle': {
                branch: 'v2.2.0',
                copyReadme: true,
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                branch: 'v1.4.0',
                copyReadme: true,
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: 'v4.1.1',
                copyReadme: true,
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: 'v2.3.1',
                copyReadme: true,
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                branch: 'v2.2.3',
                copyReadme: true,
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '1.x',
                copyReadme: true,
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
        }
    },
    '2025.4': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultSidebarSection: 'Pimcore Extensions',
        repos: {
            'pimcore/platform-version': {
                branch: '2025.4',
                copyReadme: true,
                targetDirectory: '0001_Platform_Version',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/pimcore': {
                branch: '12.3',
                copyReadme: false,
                targetDirectory: '0002_Pimcore',
                enterprise: false,
                sidebarSection: null,
            },
            'pimcore/studio-backend-bundle': {
                branch: '2025.4',
                copyReadme: true,
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/studio-ui-bundle': {
                branch: '2025.4',
                copyReadme: true,
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Studio',
                enterprise: false,
            },
            'pimcore/data-hub': {
                branch: '2.4',
                copyReadme: true,
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-importer': {
                branch: '2.4',
                copyReadme: true,
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: false,
            },
            'pimcore/data-hub-file-export': {
                branch: '3.4',
                copyReadme: true,
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: '3.5',
                copyReadme: true,
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/admin-ui-classic-light-theme-bundle': {
                branch: '2.1',
                copyReadme: true,
                targetDirectory: '0301_Light_Theme_Admin_UI',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: '1.8',
                copyReadme: true,
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/perspective-editor': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0303_Perspective_Editor',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/direct-edit': {
                branch: '2.6',
                copyReadme: true,
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: '1.9',
                copyReadme: true,
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/advanced-object-search': {
                branch: '7.1',
                copyReadme: true,
                targetDirectory: '0306_Advanced_Object_Search',
                sidebarGroup: 'Productivity',
                enterprise: false,
            },
            'pimcore/copilot-bundle': {
                branch: '2.5',
                copyReadme: true,
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                branch: 'v2.1.0',
                copyReadme: true,
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: '1.3',
                copyReadme: true,
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: '5.3',
                copyReadme: true,
                targetDirectory: '0501_Portal_Engine',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: '3.3',
                copyReadme: true,
                targetDirectory: '0502_Statistics_Explorer',
                sidebarGroup: 'Portals',
                enterprise: true,
            },
            'pimcore/ee-tinymce-bundle': {
                branch: '2.1',
                copyReadme: true,
                targetDirectory: '0600_TinyMCE_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: 'professional',
            },
            'pimcore/quill-bundle': {
                branch: '2.2',
                copyReadme: true,
                targetDirectory: '0601_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/headless-documents': {
                branch: '2.7',
                copyReadme: true,
                targetDirectory: '0602_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: '3.4',
                copyReadme: true,
                targetDirectory: '0603_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                branch: '1.7',
                copyReadme: true,
                targetDirectory: '0604_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                branch: '2.3',
                copyReadme: true,
                targetDirectory: '0605_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                branch: '5.3',
                copyReadme: true,
                targetDirectory: '0606_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/generic-data-index-bundle': {
                branch: '2.5',
                copyReadme: true,
                targetDirectory: '0607_Generic_Data_Index',
                sidebarGroup: 'Advanced Data Management',
                enterprise: false,
            },
            'pimcore/newsletter-bundle': {
                branch: '2.3',
                copyReadme: true,
                targetDirectory: '0701_Newsletter',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/google-marketing-bundle': {
                branch: '2.1',
                copyReadme: true,
                targetDirectory: '0702_Google_Marketing',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: false,
            },
            'pimcore/ee-personalization-bundle': {
                branch: '2.4',
                copyReadme: true,
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                branch: '1.6',
                copyReadme: true,
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: '4.3',
                copyReadme: true,
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: '2.4',
                copyReadme: true,
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                branch: '2.4',
                copyReadme: true,
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '1.x',
                copyReadme: true,
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
        }
    },
    '2026.1': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultBranch: '2026.1',
        defaultCopyReadme: true,
        defaultEnterprise: false,
        defaultSidebarSection: 'Pimcore Modules',
        repos: {
            'pimcore/platform-version': {
                branch: 'v2026.1.1',
                sidebarSection: null,
                targetDirectories: {
                    '01_Pimcore_Overview': { target: '0001_Pimcore_Overview' },
                    '02_Pimcore_Platform': { target: '0002_Pimcore_Platform' },
                    '03_Getting_Started':  { target: '0004_Getting_Started' },
                },
            },
            'pimcore/pimcore': {
                branch: 'v2026.1.7',
                copyReadme: false,
                targetDirectory: '0012_Pimcore',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/studio-backend-bundle': {
                branch: 'v2026.1.6',
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/studio-ui-bundle': {
                branch: 'v2026.1.7',
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/generic-data-index-bundle': {
                targetDirectory: '0105_Generic_Data_Index',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/ee-tinymce-bundle': {
                branch: 'v2026.1.2',
                targetDirectory: '0110_TinyMCE_WYSWIYG_Editor',
                sidebarGroup: 'Pimcore Core',
                enterprise: 'professional',
            },
            'pimcore/quill-bundle': {
                branch: 'v2026.1.1',
                targetDirectory: '0111_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/data-hub': {
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
            },
            'pimcore/data-importer': {
                branch: 'v2026.1.5',
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
            },
            'pimcore/data-hub-file-export': {
                branch: 'v2026.1.3',
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                branch: 'v2026.1.4',
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                branch: 'v2026.1.2',
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                branch: 'v2026.1.6',
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/direct-edit': {
                branch: 'v2026.1.3',
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                branch: 'v2026.1.1',
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/copilot-bundle': {
                branch: 'v2026.1.5',
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                branch: 'v2026.1.1',
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                branch: 'v2026.1.2',
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/studio-dashboards-bundle': {
                branch: 'v2026.1.3',
                targetDirectory: '0501_Studio_Dashboards',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                branch: 'v2026.1.6',
                targetDirectory: '0502_Portal_Engine',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                branch: 'v2026.1.2',
                targetDirectory: '0503_Statistics_Explorer',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/headless-documents': {
                branch: 'v2026.1.3',
                targetDirectory: '0602_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                branch: 'v2026.1.5',
                targetDirectory: '0603_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                branch: 'v2026.1.4',
                targetDirectory: '0604_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                branch: 'v2026.1.1',
                targetDirectory: '0605_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                branch: 'v2026.1.4',
                targetDirectory: '0606_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },

            'pimcore/ee-personalization-bundle': {
                branch: 'v2026.1.1',
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                branch: 'v2026.1.2',
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                branch: 'v2026.1.4',
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                branch: 'v2026.1.4',
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                branch: 'v2026.1.2',
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '2026.x',
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
            'pimcore/pimcore-agent-bundle': {
                branch: 'main',
                targetDirectory: '9001_Pimcore_Agent',
                enterprise: true,
                sidebarSection: 'Pimcore Labs',
            },
        }
    },
    '2026.2': {
        isVersion: true,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultBranch: '2026.2',
        defaultCopyReadme: true,
        defaultEnterprise: false,
        defaultSidebarSection: 'Pimcore Modules',
        repos: {
            'pimcore/platform-version': {
                sidebarSection: null,
                targetDirectories: {
                    '01_Pimcore_Overview': { target: '0001_Pimcore_Overview' },
                    '02_Pimcore_Platform': { target: '0002_Pimcore_Platform' },
                    '03_Getting_Started':  { target: '0004_Getting_Started' },
                },
            },
            'pimcore/pimcore': {
                copyReadme: false,
                targetDirectory: '0012_Pimcore',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/studio-backend-bundle': {
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/studio-ui-bundle': {
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/generic-data-index-bundle': {
                targetDirectory: '0105_Generic_Data_Index',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/ee-tinymce-bundle': {
                targetDirectory: '0110_TinyMCE_WYSWIYG_Editor',
                sidebarGroup: 'Pimcore Core',
                enterprise: 'professional',
            },
            'pimcore/quill-bundle': {
                targetDirectory: '0111_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/data-hub': {
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
            },
            'pimcore/data-importer': {
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
            },
            'pimcore/data-hub-file-export': {
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/direct-edit': {
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/copilot-bundle': {
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/studio-dashboards-bundle': {
                targetDirectory: '0501_Studio_Dashboards',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                targetDirectory: '0502_Portal_Engine',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                targetDirectory: '0503_Statistics_Explorer',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/headless-documents': {
                targetDirectory: '0602_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                targetDirectory: '0603_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                targetDirectory: '0604_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                targetDirectory: '0605_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                targetDirectory: '0606_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },

            'pimcore/ee-personalization-bundle': {
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '2026.x',
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
            'pimcore/pimcore-agent-bundle': {
                branch: 'main',
                targetDirectory: '9001_Pimcore_Agent',
                enterprise: true,
                sidebarSection: 'Pimcore Labs',
            },
        }
    },
    '2026.x': {
        isVersion: false,
        sidebar: './bin/resources/sidebars.json',
        index: './bin/resources/00_index.md',
        defaultBranch: '2026.x',
        defaultCopyReadme: true,
        defaultEnterprise: false,
        defaultSidebarSection: 'Pimcore Modules',
        repos: {
            'pimcore/platform-version': {
                sidebarSection: null,
                targetDirectories: {
                    '01_Pimcore_Overview': { target: '0001_Pimcore_Overview' },
                    '02_Pimcore_Platform': { target: '0002_Pimcore_Platform' },
                    '03_Getting_Started':  { target: '0004_Getting_Started' },
                },
            },
            'pimcore/pimcore': {
                copyReadme: false,
                targetDirectory: '0012_Pimcore',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/studio-backend-bundle': {
                targetDirectory: '0101_Studio_Backend',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/studio-ui-bundle': {
                targetDirectory: '0101_Studio_UI',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/generic-data-index-bundle': {
                targetDirectory: '0105_Generic_Data_Index',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/ee-tinymce-bundle': {
                targetDirectory: '0110_TinyMCE_WYSWIYG_Editor',
                sidebarGroup: 'Pimcore Core',
                enterprise: 'professional',
            },
            'pimcore/quill-bundle': {
                targetDirectory: '0111_Quill_WYSWIYG_Editor',
                sidebarGroup: 'Pimcore Core',
            },
            'pimcore/data-hub': {
                targetDirectory: '0201_Datahub',
                sidebarGroup: 'Data Onboarding & Distribution',
            },
            'pimcore/data-importer': {
                targetDirectory: '0202_Data_Importer',
                sidebarGroup: 'Data Onboarding & Distribution',
            },
            'pimcore/data-hub-file-export': {
                targetDirectory: '0203_Datahub_File_Export',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-simple-rest': {
                targetDirectory: '0204_Datahub_Simple_Rest',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/data-hub-webhooks': {
                targetDirectory: '0205_Datahub_Webhooks',
                sidebarGroup: 'Data Onboarding & Distribution',
                enterprise: true,
            },
            'pimcore/backend-power-tools-bundle': {
                targetDirectory: '0302_Backend_Power_Tools',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/direct-edit': {
                targetDirectory: '0304_Direct_Edit',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/workflow-designer': {
                targetDirectory: '0305_Worfklow_Designer',
                sidebarGroup: 'Productivity',
                enterprise: true,
            },
            'pimcore/copilot-bundle': {
                targetDirectory: '0401_Copilot',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/copilot-showcase-bundle': {
                targetDirectory: '0402_Copilot_Showcases',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/workflow-automation-integration-bundle': {
                targetDirectory: '0403_Workflow_Automation',
                sidebarGroup: 'Automation',
                enterprise: true,
            },
            'pimcore/studio-dashboards-bundle': {
                targetDirectory: '0501_Studio_Dashboards',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/portal-engine': {
                targetDirectory: '0502_Portal_Engine',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/statistics-explorer': {
                targetDirectory: '0503_Statistics_Explorer',
                sidebarGroup: 'Portals & Dashboards',
                enterprise: true,
            },
            'pimcore/headless-documents': {
                targetDirectory: '0602_Headless_Documents',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/asset-metadata-class-definitions': {
                targetDirectory: '0603_Enterprise_Metadata',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/data-quality-management-bundle': {
                targetDirectory: '0604_Data_Quality_Management',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-web-to-print-bundle': {
                targetDirectory: '0605_Web_To_Print',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },
            'pimcore/ee-customer-data-framework': {
                targetDirectory: '0606_Customer_Management_Framework',
                sidebarGroup: 'Advanced Data Management',
                enterprise: true,
            },

            'pimcore/ee-personalization-bundle': {
                targetDirectory: '0703_Targeting',
                sidebarGroup: 'Marketing & Personalization',
                enterprise: true,
            },
            'pimcore/openid-connect': {
                targetDirectory: '0801_OpenID_Connect',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/translations-provider-interfaces': {
                targetDirectory: '0802_Translation_Provider_Interfaces',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/data-hub-productsup': {
                targetDirectory: '0803_Datahub_Productsup',
                sidebarGroup: 'Integrations',
                enterprise: true,
            },
            'pimcore/ee-ecommerce-framework-bundle': {
                targetDirectory: '1010_Ecommerce_Framework',
                enterprise: true,
            },
            'pimcore/paas': {
                branch: '2026.x',
                targetDirectory: '8080_Paas',
                enterprise: true,
                sidebarSection: 'Pimcore Operations',
            },
            'pimcore/pimcore-agent-bundle': {
                branch: 'main',
                targetDirectory: '9001_Pimcore_Agent',
                enterprise: true,
                sidebarSection: 'Pimcore Labs',
            },
        }
    }
}

const baseUrl = '/platform';

module.exports = { platformVersions, baseUrl };
